name: PKGBUILD-validate

on:
  push:
    tags:
    - '*'
  workflow_dispatch:

jobs:
  validation:
    runs-on: ubuntu-latest
    name: Validate a Pull Request and commit
    steps:
      - uses: actions/checkout@v4

      - name: Validate PKGBUILD
        id: validate-pkgbuild
        uses: 2m/arch-pkgbuild-builder@v1.21
        with:
          target: 'pkgbuild'
          pkgname: '.build_action'

      - name: Validate SRCINFO
        id: validate-srcinfo
        uses: 2m/arch-pkgbuild-builder@v1.21
        with:
          target: 'srcinfo'
          pkgname: '.build_action'

#      - name: Validate binary
#        id: validate-3proxy
#        uses: 2m/arch-pkgbuild-builder@v1.21
#        with:
#          target: 'run'
#          pkgname: '.build_action'
#          command: '3proxy -v'
#
#      - name: Validate binary
#        id: validate-socks
#        uses: 2m/arch-pkgbuild-builder@v1.21
#        with:
#          target: 'run'
#          pkgname: '.build_action'
#          command: 'socks -v'
#
#      - name: Validate binary
#        id: validate-3proxy-proxy
#        uses: 2m/arch-pkgbuild-builder@v1.21
#        with:
#          target: 'run'
#          pkgname: '.build_action'
#          command: '3proxy-proxy -v'
